# Generated by Django 5.2.1 on 2025-05-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='contribution_date',
            field=models.DateTimeField(blank=True, help_text='Date when the contribution was made. Defaults to creation time if not specified.', null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='multiplier_at_creation',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
