# Generated by Django 5.2.1 on 2025-05-23 14:15

import contributions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0004_contributiontype_max_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='evidence_url',
            field=models.URLField(blank=True, help_text='DEPRECATED: Use Evidence model instead'),
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, help_text='Description of the evidence')),
                ('url', models.URLField(blank=True, help_text='Link to external evidence')),
                ('file', models.FileField(blank=True, help_text='Upload file as evidence', null=True, upload_to=contributions.models.evidence_file_path)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='contributions.contribution')),
            ],
            options={
                'verbose_name': 'Evidence',
                'verbose_name_plural': 'Evidence Items',
            },
        ),
    ]
