# Generated by Django 5.2.1 on 2025-05-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0006_migrate_evidence_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='evidence_url',
        ),
    ]
