# Generated by Django 5.2.1 on 2025-06-05 12:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0007_remove_contribution_evidence_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='contributions.contribution'),
        ),
        migrations.CreateModel(
            name='SubmittedContribution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contribution_date', models.DateTimeField(help_text='Date when the contribution was made')),
                ('notes', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('more_info_needed', 'More Information Needed')], default='pending', max_length=20)),
                ('staff_reply', models.TextField(blank=True, help_text='Response from staff member')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('last_edited_at', models.DateTimeField(blank=True, null=True)),
                ('contribution_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_contributions', to='contributions.contributiontype')),
                ('converted_contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_submission', to='contributions.contribution')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submitted Contribution',
                'verbose_name_plural': 'Submitted Contributions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='submitted_contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='contributions.submittedcontribution'),
        ),
    ]
