# Generated by Django 5.2.1 on 2025-08-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0008_alter_evidence_contribution_submittedcontribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributiontype',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Include this contribution type by default when creating validators'),
        ),
    ]
