# Generated by Django 5.2.1 on 2025-08-15 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0009_add_is_default_to_contributiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Short title for the highlight', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of why this contribution is noteworthy')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this highlight should be shown')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which highlights are displayed (lower numbers first)')),
                ('featured_until', models.DateTimeField(blank=True, help_text='Optional: Hide this highlight after this date', null=True)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='contributions.contribution')),
            ],
            options={
                'verbose_name': 'Contribution Highlight',
                'verbose_name_plural': 'Contribution Highlights',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
