# Generated by Django 5.2.1 on 2025-08-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0010_contributionhighlight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributionhighlight',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contribution Highlight', 'verbose_name_plural': 'Contribution Highlights'},
        ),
        migrations.RemoveField(
            model_name='contributionhighlight',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='contributionhighlight',
            name='featured_until',
        ),
        migrations.RemoveField(
            model_name='contributionhighlight',
            name='is_active',
        ),
    ]
