# Generated by Django 5.2.1 on 2025-08-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0009_add_is_default_to_contributiontype'),
        ('contributions', '0011_create_node_upgrade_contribution_type'),
    ]

    operations = [
    ]
