# Generated by Django 5.2.1 on 2025-08-15 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0012_merge_20250815_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('profile_model', models.CharField(blank=True, help_text="App.Model reference for the profile model (e.g., 'validators.Validator')", max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contributiontype',
            name='category',
            field=models.ForeignKey(blank=True, help_text='The category this contribution type belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contribution_types', to='contributions.category'),
        ),
    ]
