# Generated by Django 5.2.1 on 2025-08-16 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0011_alter_contributionhighlight_options_and_more'),
        ('contributions', '0012_merge_20250815_1512'),
    ]

    operations = [
    ]
