# Generated by Django 5.2.1 on 2025-08-15 20:52

from django.db import migrations


def create_initial_categories(apps, schema_editor):
    """Create initial categories and assign existing contribution types to validator category."""
    Category = apps.get_model('contributions', 'Category')
    ContributionType = apps.get_model('contributions', 'ContributionType')
    
    # Create Validator category
    validator_category = Category.objects.create(
        name='Validator',
        slug='validator',
        description='Validators who run nodes and maintain the network',
        profile_model='validators.Validator'
    )
    
    # Create Builder category
    builder_category = Category.objects.create(
        name='Builder',
        slug='builder',
        description='Developers who build on and contribute to the ecosystem',
        profile_model='builders.Builder'
    )
    
    # Create Steward category
    steward_category = Category.objects.create(
        name='Steward',
        slug='steward',
        description='Community members who support and grow the ecosystem',
        profile_model='stewards.Steward'
    )
    
    # Assign all existing contribution types to Validator category
    ContributionType.objects.update(category=validator_category)


def reverse_categories(apps, schema_editor):
    """Remove categories and unassign contribution types."""
    Category = apps.get_model('contributions', 'Category')
    ContributionType = apps.get_model('contributions', 'ContributionType')
    
    # Unassign all contribution types
    ContributionType.objects.update(category=None)
    
    # Delete categories
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0013_category_contributiontype_category'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories, reverse_categories),
    ]