# Generated by Django 5.2.1 on 2025-08-16 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0013_merge_20250816_0051'),
        ('contributions', '0013_merge_20250816_0331'),
        ('contributions', '0015_merge_20250816_0226'),
    ]

    operations = [
    ]
