# Generated by Django 5.1.2 on 2024-08-16 17:52

from django.db import migrations


def add_journey_contribution_types(apps, schema_editor):
    ContributionType = apps.get_model('contributions', 'ContributionType')
    Category = apps.get_model('contributions', 'Category')
    
    # Get or create validator category
    validator_category, _ = Category.objects.get_or_create(
        slug='validator',
        defaults={
            'name': 'Validator',
            'description': 'Validator category'
        }
    )
    
    # Get or create builder category
    builder_category, _ = Category.objects.get_or_create(
        slug='builder',
        defaults={
            'name': 'Builder',
            'description': 'Builder category'
        }
    )
    
    # Create Validator Waitlist contribution type
    ContributionType.objects.get_or_create(
        slug='validator-waitlist',
        defaults={
            'name': 'Validator Waitlist',
            'description': 'Joined the validator waitlist by completing the interest form',
            'category': validator_category,
            'min_points': 20,
            'max_points': 20,
            'is_default': False
        }
    )
    
    # Create Builder Initiate contribution type
    ContributionType.objects.get_or_create(
        slug='builder-initiate',
        defaults={
            'name': 'Builder Initiate',
            'description': 'Started the builder journey by deploying first contract',
            'category': builder_category,
            'min_points': 20,
            'max_points': 20,
            'is_default': False
        }
    )


def remove_journey_contribution_types(apps, schema_editor):
    ContributionType = apps.get_model('contributions', 'ContributionType')
    ContributionType.objects.filter(slug__in=['validator-waitlist', 'builder-initiate']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0016_merge_20250816_0427'),
    ]

    operations = [
        migrations.RunPython(add_journey_contribution_types, remove_journey_contribution_types),
    ]