# Generated by Django migration

from django.db import migrations

def rename_builder_initiate(apps, schema_editor):
    """Rename builder-initiate slug to builder-welcome"""
    ContributionType = apps.get_model('contributions', 'ContributionType')
    
    try:
        builder_initiate = ContributionType.objects.get(slug='builder-initiate')
        builder_initiate.slug = 'builder-welcome'
        builder_initiate.name = 'Builder Welcome'
        builder_initiate.description = 'Welcome to the GenLayer builder community!'
        builder_initiate.save()
    except ContributionType.DoesNotExist:
        # If it doesn't exist, that's okay - might be a fresh install
        pass

def reverse_rename(apps, schema_editor):
    """Reverse the rename for rollback"""
    ContributionType = apps.get_model('contributions', 'ContributionType')
    
    try:
        builder_welcome = ContributionType.objects.get(slug='builder-welcome')
        builder_welcome.slug = 'builder-initiate'
        builder_welcome.name = 'Builder Initiate'
        builder_welcome.description = 'Started the builder journey'
        builder_welcome.save()
    except ContributionType.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0017_add_journey_contribution_types'),
    ]

    operations = [
        migrations.RunPython(rename_builder_initiate, reverse_rename),
    ]