# Generated by Django 5.2.5 on 2025-08-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0018_rename_builder_initiate_to_welcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributiontype',
            name='is_submittable',
            field=models.BooleanField(default=True, help_text='Whether this contribution type can be submitted by users'),
        ),
    ]
