# Generated by Django 5.2.5 on 2025-08-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0019_add_is_submittable'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedcontribution',
            name='suggested_points',
            field=models.PositiveIntegerField(blank=True, help_text='Pre-calculated points for automatic submissions (e.g., node upgrades)', null=True),
        ),
    ]
