# Generated by Django 5.2.5 on 2025-08-27 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0020_add_suggested_points_and_node_version_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributionhighlight',
            options={'ordering': ['-contribution__contribution_date'], 'verbose_name': 'Contribution Highlight', 'verbose_name_plural': 'Contribution Highlights'},
        ),
    ]
