# Generated by Django 5.2.5 on 2025-08-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0021_alter_contributionhighlight_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='frozen_global_points',
            field=models.PositiveIntegerField(default=0, help_text='Global points calculated as points × multiplier. Can be manually adjusted in admin.'),
        ),
    ]
