# Generated by Django 5.2.5 on 2025-08-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0022_alter_contribution_frozen_global_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='frozen_global_points',
            field=models.PositiveIntegerField(default=0, help_text='Global points calculated as points × multiplier.'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='multiplier_at_creation',
            field=models.DecimalField(decimal_places=2, help_text='Multiplier value at the time of contribution creation.', max_digits=5, null=True),
        ),
    ]
