# Generated by Django 5.2.6 on 2025-09-23 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0023_make_points_fields_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributiontype',
            name='examples',
            field=models.JSONField(blank=True, default=list, help_text='Example entries for this contribution type (array of short strings)'),
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the mission', max_length=200)),
                ('short_description', models.CharField(help_text='Brief description shown on cards', max_length=300)),
                ('long_description', models.TextField(help_text='Detailed description shown on dedicated page')),
                ('start_date', models.DateTimeField(blank=True, help_text='When this mission becomes active (optional)', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When this mission expires (optional)', null=True)),
                ('contribution_type', models.ForeignKey(help_text='The contribution type this mission is related to', on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='contributions.contributiontype')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'ordering': ['-created_at'],
            },
        ),
    ]
