# Generated by Django 5.2.5 on 2025-10-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0024_contributiontype_examples_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributiontype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
