# Generated by Django 5.2.6 on 2025-09-17 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0024_add_examples_and_icon_to_contributiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the highlight', max_length=200)),
                ('short_description', models.CharField(help_text='Brief description shown on cards', max_length=300)),
                ('expanded_description', models.TextField(help_text='Detailed description shown in modal')),
                ('start_date', models.DateTimeField(blank=True, help_text='When this highlight becomes active (optional)', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When this highlight expires (optional)', null=True)),
                ('extra_points', models.PositiveIntegerField(blank=True, help_text='Optional extra points for this highlight period', null=True)),
                ('contribution_type', models.ForeignKey(help_text='The contribution type this highlight is related to', on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='contributions.contributiontype')),
            ],
            options={
                'verbose_name': 'Highlight',
                'verbose_name_plural': 'Highlights',
                'ordering': ['-created_at'],
            },
        ),
    ]
