# Generated by Django 5.2.7 on 2025-10-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0025_remove_contributiontype_name_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributiontype',
            options={'ordering': ['category__name', 'name']},
        ),
    ]
