# Generated by Django 5.2.6 on 2025-09-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0025_highlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='extra_points',
        ),
    ]
