# Generated by Django 5.2.6 on 2025-10-13 16:21

import contributions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0026_alter_contributiontype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(blank=True, help_text='DEPRECATED: File uploads are not currently supported. Use URL instead.', null=True, upload_to=contributions.models.evidence_file_path),
        ),
    ]
