# Generated by Django 5.2.8 on 2025-11-26 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0028_add_mission_to_submissions_and_contributions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedcontribution',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Steward assigned to review this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
