# Generated by Django 5.2.10 on 2026-01-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0029_submittedcontribution_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title of the startup request', max_length=200)),
                ('description', models.TextField(help_text='Full description (supports Markdown)')),
                ('short_description', models.CharField(help_text='Brief description shown in listing (plain text)', max_length=300)),
                ('documents', models.JSONField(blank=True, default=list, help_text='Array of document objects: [{title, url, type}]')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this startup request is currently visible')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
            ],
            options={
                'verbose_name': 'Startup Request',
                'verbose_name_plural': 'Startup Requests',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
