# Generated by Django 5.2.6 on 2025-10-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0030_migrate_notifications_to_django_notifications_hq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
