# Generated by Django 6.0.2 on 2026-02-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0032_submittedcontribution_proposal_fields_submissionnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionnote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='submissionnote',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Structured data: action, points, staff_reply, template_id, flags, confidence'),
        ),
    ]
