# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0033_alter_submissionnote_options_featuredcontent'),
    ]

    operations = [
        # Rename hero_image_url -> hero_image_link to free up the name for the serializer
        migrations.RenameField(
            model_name='featuredcontent',
            old_name='hero_image_url',
            new_name='hero_image_link',
        ),
        # Add hero_image FileField for uploaded background images
        migrations.AddField(
            model_name='featuredcontent',
            name='hero_image',
            field=models.FileField(blank=True, null=True, upload_to='featured/'),
        ),
        # Add user_profile_image FileField for user avatar uploads
        migrations.AddField(
            model_name='featuredcontent',
            name='user_profile_image',
            field=models.FileField(blank=True, null=True, upload_to='featured/avatars/'),
        ),
    ]
