# Generated by Django 6.0.2 on 2026-02-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0034_featuredcontent_image_fields'),
    ]

    operations = [
        # Remove FileFields (no longer needed, replaced by Cloudinary URLs)
        migrations.RemoveField(
            model_name='featuredcontent',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='featuredcontent',
            name='user_profile_image',
        ),
        # Rename hero_image_link back to hero_image_url (was renamed in migration 0034)
        migrations.RenameField(
            model_name='featuredcontent',
            old_name='hero_image_link',
            new_name='hero_image_url',
        ),
        # Update hero_image_url field definition to match new model
        migrations.AlterField(
            model_name='featuredcontent',
            name='hero_image_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for hero/background image', max_length=500),
        ),
        # Add new Cloudinary fields
        migrations.AddField(
            model_name='featuredcontent',
            name='hero_image_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for hero image', max_length=255),
        ),
        migrations.AddField(
            model_name='featuredcontent',
            name='user_profile_image_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for user avatar in featured card', max_length=500),
        ),
        migrations.AddField(
            model_name='featuredcontent',
            name='user_profile_image_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for user avatar', max_length=255),
        ),
    ]
