# Generated by Django 6.0.2 on 2026-02-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0035_remove_featuredcontent_hero_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=10)),
                ('icon', models.CharField(blank=True, help_text='Optional icon name (frontend defaults by type)', max_length=50)),
                ('text', models.TextField(help_text='Alert message text')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('start_date', models.DateTimeField(blank=True, help_text='When this alert becomes visible (optional)', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When this alert expires (optional)', null=True)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
