# Generated by Django 6.0.3 on 2026-03-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0037_seed_featured_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredcontent',
            old_name='subtitle',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='featuredcontent',
            name='hero_image_public_id',
        ),
        migrations.RemoveField(
            model_name='featuredcontent',
            name='hero_image_url',
        ),
        migrations.RemoveField(
            model_name='featuredcontent',
            name='user_profile_image_public_id',
        ),
        migrations.RemoveField(
            model_name='featuredcontent',
            name='user_profile_image_url',
        ),
        migrations.AddField(
            model_name='featuredcontent',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured/'),
        ),
        migrations.AddField(
            model_name='featuredcontent',
            name='user_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured/avatars/'),
        ),
    ]
