# Generated by Django 6.0.3 on 2026-03-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0038_rename_subtitle_featuredcontent_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredcontent',
            name='hero_image_mobile',
            field=models.ImageField(blank=True, help_text='Mobile variant (<768px). Falls back to hero_image if empty.', null=True, upload_to='featured/'),
        ),
        migrations.AddField(
            model_name='featuredcontent',
            name='hero_image_tablet',
            field=models.ImageField(blank=True, help_text='Tablet variant (768-1023px). Falls back to hero_image if empty.', null=True, upload_to='featured/'),
        ),
    ]
