# Generated by Django 6.0.3 on 2026-03-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0039_add_responsive_hero_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredcontent',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='featuredcontent',
            name='hero_image_mobile',
        ),
        migrations.RemoveField(
            model_name='featuredcontent',
            name='hero_image_tablet',
        ),
        migrations.RemoveField(
            model_name='featuredcontent',
            name='user_profile_image',
        ),
        migrations.AddField(
            model_name='featuredcontent',
            name='hero_image_mobile_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for mobile hero image', max_length=255),
        ),
        migrations.AddField(
            model_name='featuredcontent',
            name='hero_image_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for hero image', max_length=255),
        ),
        migrations.AddField(
            model_name='featuredcontent',
            name='hero_image_tablet_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for tablet hero image', max_length=255),
        ),
        migrations.AddField(
            model_name='featuredcontent',
            name='hero_image_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for hero image', max_length=500),
        ),
        migrations.AddField(
            model_name='featuredcontent',
            name='hero_image_url_mobile',
            field=models.URLField(blank=True, help_text='Cloudinary URL for mobile hero image (<768px). Falls back to hero_image_url if empty.', max_length=500),
        ),
        migrations.AddField(
            model_name='featuredcontent',
            name='hero_image_url_tablet',
            field=models.URLField(blank=True, help_text='Cloudinary URL for tablet hero image (768-1023px). Falls back to hero_image_url if empty.', max_length=500),
        ),
        migrations.AddField(
            model_name='featuredcontent',
            name='user_profile_image_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for user profile image', max_length=255),
        ),
        migrations.AddField(
            model_name='featuredcontent',
            name='user_profile_image_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for user profile image', max_length=500),
        ),
    ]
