# Generated by Django 5.2.6 on 2026-03-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0041_merge_submissions_and_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocklistedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url_prefix', models.URLField(help_text='URL prefix to block (e.g. https://genlayer.com). Matches the prefix and any subpaths.', unique=True)),
                ('reason', models.CharField(blank=True, help_text='Why this URL is blocklisted (for internal reference).', max_length=200)),
            ],
            options={
                'verbose_name': 'Blocklisted URL',
                'verbose_name_plural': 'Blocklisted URLs',
                'ordering': ['url_prefix'],
            },
        ),
    ]
