# Generated by Django 5.2.6 on 2026-04-01 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0043_seed_blocklisted_urls'),
        ('stewards', '0009_tier1_review_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedcontribution',
            name='proposed_confidence',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], help_text='Confidence level of the proposal', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='submittedcontribution',
            name='proposed_template',
            field=models.ForeignKey(blank=True, help_text='Review template used for the proposal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_submissions', to='stewards.reviewtemplate'),
        ),
    ]
