# Generated by Django 5.2.6 on 2026-04-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0047_create_community_onboarding_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Optional title for the contribution', max_length=200),
        ),
        migrations.AddField(
            model_name='submittedcontribution',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Optional title for the submission', max_length=200),
        ),
    ]
