# Generated by Django 6.0.4 on 2026-04-13 15:14

from django.db import migrations, models


def migrate_is_active_to_status(apps, schema_editor):
    FeaturedContent = apps.get_model('contributions', 'FeaturedContent')
    FeaturedContent.objects.filter(is_active=False).update(status='idle')


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0048_contribution_title_submittedcontribution_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredcontent',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('idle', 'Idle')], default='active', max_length=10),
        ),
        migrations.RunPython(migrate_is_active_to_status, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='featuredcontent',
            name='is_active',
        ),
    ]
