# Generated by Django 6.0.4 on 2026-04-15 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0049_featuredcontent_status_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceURLType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('url_patterns', models.JSONField(default=list, help_text='List of regex patterns to match URLs of this type')),
                ('is_generic', models.BooleanField(default=False, help_text='If True, this is the fallback type for unrecognized URLs')),
                ('order', models.PositiveIntegerField(default=0)),
                ('handle_extract_pattern', models.CharField(blank=True, help_text="Regex with named group 'handle' to extract owner/handle from URL", max_length=500)),
                ('ownership_social_account', models.CharField(blank=True, help_text="Social account type for ownership checks: 'twitter' or 'github'", max_length=20)),
            ],
            options={
                'verbose_name': 'Evidence URL Type',
                'verbose_name_plural': 'Evidence URL Types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='contributiontype',
            name='accepted_evidence_url_types',
            field=models.ManyToManyField(blank=True, help_text='Accepted evidence URL types. Empty means all types are accepted.', related_name='contribution_types', to='contributions.evidenceurltype'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='url_type',
            field=models.ForeignKey(blank=True, help_text='Auto-detected URL type for this evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_items', to='contributions.evidenceurltype'),
        ),
    ]
