# Generated by Django 6.0.4 on 2026-04-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0051_seed_evidence_url_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='normalized_url',
            field=models.CharField(blank=True, db_index=True, help_text='Normalized URL for fast duplicate detection', max_length=2000),
        ),
    ]
