# Generated by Django 6.0.4 on 2026-04-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0052_contributiontype_required_evidence_url_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributiontype',
            name='show_in_contributions',
            field=models.BooleanField(default=False, help_text='Show this contribution type in the public Contributions list even when it is not directly submittable. Intended for informational / mission-host types whose missions carry the actual submissions.'),
        ),
    ]
