# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0056_submittedcontribution_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributiontype',
            name='max_submissions',
            field=models.PositiveIntegerField(
                blank=True,
                help_text=(
                    'Maximum number of non-rejected submissions allowed for '
                    'this contribution type. Leave blank for unlimited.'
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='mission',
            name='max_submissions',
            field=models.PositiveIntegerField(
                blank=True,
                help_text=(
                    'Maximum number of non-rejected submissions allowed for '
                    'this mission. Leave blank for unlimited.'
                ),
                null=True,
            ),
        ),
    ]
