# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0057_contribution_submission_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='max_submissions_per_user',
            field=models.PositiveIntegerField(
                blank=True,
                help_text=(
                    'Maximum number of non-rejected submissions allowed per '
                    'user for this mission. Leave blank for unlimited.'
                ),
                null=True,
            ),
        ),
    ]
