# Generated by Django 6.0.5 on 2026-05-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0059_add_canceled_submission_state'),
        ('social_connections', '0003_discordrolesynclock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributiontype',
            name='required_discord_roles',
            field=models.ManyToManyField(blank=True, help_text='Discord guild roles required for submission. If set, the submitter must have at least one of these roles.', related_name='required_by_contribution_types', to='social_connections.discordrole'),
        ),
    ]
