# Generated by Django 6.0.5 on 2026-05-24

import contributions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0060_contributiontype_required_discord_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredcontent',
            name='hero_placements',
            field=models.JSONField(
                blank=True,
                default=contributions.models.default_featured_hero_placements,
                help_text=(
                    "Hero banner placements. Use 'all' to show everywhere, or select "
                    "specific surfaces such as overview, builder, validator, and community."
                ),
            ),
        ),
    ]
