# Generated by Codex on 2026-06-04

from django.db import migrations, models


def dedupe_featured_content(apps, schema_editor):
    FeaturedContent = apps.get_model('contributions', 'FeaturedContent')
    db_alias = schema_editor.connection.alias

    duplicate_groups = (
        FeaturedContent.objects.using(db_alias)
        .values('content_type', 'title')
        .annotate(count=models.Count('id'), keep_id=models.Min('id'))
        .filter(count__gt=1)
    )

    for group in duplicate_groups:
        (
            FeaturedContent.objects.using(db_alias)
            .filter(content_type=group['content_type'], title=group['title'])
            .exclude(id=group['keep_id'])
            .delete()
        )


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0062_merge_0061_community_discord_xp_0061_featuredcontent_hero_placements'),
    ]

    operations = [
        migrations.RunPython(dedupe_featured_content, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='featuredcontent',
            constraint=models.UniqueConstraint(
                fields=('content_type', 'title'),
                name='unique_featured_content_type_title',
            ),
        ),
    ]
