# Generated by Codex on 2026-06-05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contributions', '0063_featuredcontent_unique_content_type_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributiontype',
            name='review_flow',
            field=models.CharField(
                choices=[
                    ('standard', 'Standard'),
                    ('builder_project', 'Builder Project'),
                ],
                default='standard',
                help_text=(
                    'Steward review workflow for this contribution type. '
                    'Builder Project flow requires structured rubric proposals.'
                ),
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name='ProjectMilestoneReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_flow', models.CharField(
                    choices=[
                        ('standard', 'Standard'),
                        ('builder_project', 'Builder Project'),
                    ],
                    default='builder_project',
                    max_length=30,
                )),
                ('action', models.CharField(
                    choices=[
                        ('accept', 'Accept'),
                        ('reject', 'Reject'),
                        ('more_info', 'More Info'),
                    ],
                    max_length=20,
                )),
                ('confidence', models.CharField(
                    blank=True,
                    choices=[
                        ('high', 'High'),
                        ('medium', 'Medium'),
                        ('low', 'Low'),
                    ],
                    max_length=10,
                    null=True,
                )),
                ('gate_failures', models.JSONField(blank=True, default=list)),
                ('sections', models.JSONField(blank=True, default=dict)),
                ('extras', models.JSONField(blank=True, default=list)),
                ('overall_reason', models.TextField(blank=True)),
                ('proposer', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='project_milestone_reviews',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('submitted_contribution', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='project_milestone_review',
                    to='contributions.submittedcontribution',
                )),
            ],
            options={
                'verbose_name': 'Builder Project Review',
                'verbose_name_plural': 'Builder Project Reviews',
                'ordering': ['-updated_at'],
            },
        ),
    ]
