# Generated by Codex on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0064_project_milestone_review_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmilestonereview',
            name='review_flow',
            field=models.CharField(
                choices=[('builder_project', 'Builder Project')],
                default='builder_project',
                editable=False,
                max_length=30,
            ),
        ),
        migrations.AddConstraint(
            model_name='projectmilestonereview',
            constraint=models.CheckConstraint(
                condition=models.Q(('review_flow', 'builder_project')),
                name='project_milestone_review_builder_flow',
            ),
        ),
    ]
