# Generated by Django 6.0.6 on 2026-06-10 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0065_project_review_builder_only'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributionhighlight',
            options={'ordering': ['-created_at', '-contribution__contribution_date'], 'verbose_name': 'Contribution Highlight', 'verbose_name_plural': 'Contribution Highlights'},
        ),
        migrations.AlterField(
            model_name='evidence',
            name='url',
            field=models.URLField(blank=True, help_text='Link to external evidence', validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
