# Generated by Django 6.0.6 on 2026-06-12 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_social_task_xp_states(apps, schema_editor):
    """Create pending Discord XP states for existing community social task completions."""
    ContributionDiscordXPState = apps.get_model('contributions', 'ContributionDiscordXPState')
    SocialTaskCompletion = apps.get_model('social_tasks', 'SocialTaskCompletion')

    completions = SocialTaskCompletion.objects.filter(
        task__category__slug='community',
        discord_xp_state__isnull=True,
    )
    ContributionDiscordXPState.objects.bulk_create([
        ContributionDiscordXPState(
            social_task_completion=completion,
            status='pending',
            awarded_amount=0,
        )
        for completion in completions.iterator()
    ], batch_size=500)


def remove_social_task_xp_states(apps, schema_editor):
    ContributionDiscordXPState = apps.get_model('contributions', 'ContributionDiscordXPState')
    ContributionDiscordXPState.objects.filter(social_task_completion__isnull=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0068_split_projects_and_milestones'),
        ('social_tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributiondiscordxpstate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='contributiondiscordxpstate',
            name='social_task_completion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discord_xp_state', to='social_tasks.socialtaskcompletion'),
        ),
        migrations.AlterField(
            model_name='contributiondiscordxpstate',
            name='contribution',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discord_xp_state', to='contributions.contribution'),
        ),
        migrations.AddConstraint(
            model_name='contributiondiscordxpstate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contribution__isnull', False), ('social_task_completion__isnull', True)), models.Q(('contribution__isnull', True), ('social_task_completion__isnull', False)), _connector='OR'), name='discord_xp_state_single_source'),
        ),
        migrations.RunPython(backfill_social_task_xp_states, remove_social_task_xp_states),
    ]
