# Generated by Django 6.0.6 on 2026-06-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0074_update_creator_category_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributiontype',
            name='required_evidence_url_type_groups',
            field=models.JSONField(blank=True, default=list, help_text='List of EvidenceURLType slug groups, e.g. [["studio-contract", "github-repo"], ["genlayer-explorer-contract"]]. A submission must have at least one evidence URL matching each group (AND across groups, OR within a group). Empty = no group requirement.'),
        ),
    ]
