# Generated by Django 6.0.6 on 2026-07-10 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0078_create_project_review_reward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionStateTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('submitted', 'Submitted'), ('review', 'Steward Review'), ('bulk_reject', 'Bulk Reject'), ('gate_reject', 'AI Gate Reject'), ('edited', 'Edited by Submitter'), ('canceled', 'Canceled by Submitter'), ('appeal', 'Appeal'), ('evidence_added', 'Evidence Added'), ('admin', 'Admin Edit')], max_length=20)),
                ('from_state', models.CharField(blank=True, default='', help_text='State before the event; empty for the initial submission', max_length=20)),
                ('to_state', models.CharField(max_length=20)),
                ('actor', models.ForeignKey(blank=True, help_text='Who caused the event: submitter, steward, AI steward, or admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_state_transitions', to=settings.AUTH_USER_MODEL)),
                ('submitted_contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_transitions', to='contributions.submittedcontribution')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['submitted_contribution', 'created_at'], name='sub_trans_sub_created_idx'), models.Index(fields=['event', 'created_at'], name='sub_trans_event_created_idx')],
            },
        ),
    ]
