# Generated by Django 6.0.6 on 2026-07-12 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0079_submissionstatetransition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal_source', models.CharField(choices=[('review_proposal', 'Review proposal'), ('submission_note', 'Submission note')], max_length=20)),
                ('proposal_source_id', models.PositiveBigIntegerField()),
                ('proposal_ref', models.DateTimeField()),
                ('verdict', models.CharField(choices=[('agree', 'Agree'), ('agree_with_corrections', 'Agree with corrections'), ('disagree', 'Disagree')], max_length=30)),
                ('correct_decision', models.CharField(blank=True, choices=[('accept', 'Accept'), ('reject', 'Reject'), ('more_info', 'Request more information'), ('skip', 'Skip')], default='', max_length=20)),
                ('gate_failures', models.JSONField(blank=True, default=list)),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('error_claims', models.JSONField(blank=True, default=list)),
                ('reviewed_commit_sha', models.CharField(blank=True, default='', max_length=40)),
                ('review_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_feedback', to='contributions.reviewproposal')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_review_feedback', to=settings.AUTH_USER_MODEL)),
                ('submitted_contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to='contributions.submittedcontribution')),
            ],
            options={
                'indexes': [models.Index(fields=['updated_at'], name='ai_feedback_updated_idx')],
                'constraints': [models.UniqueConstraint(fields=('submitted_contribution', 'reviewer', 'proposal_source', 'proposal_source_id'), name='unique_ai_feedback_source_reviewer')],
            },
        ),
    ]
