# Generated by Django 6.0.6 on 2026-07-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0082_contributiontype_weekly_user_submission_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributiontype',
            name='escalation_threshold_points',
            field=models.PositiveIntegerField(blank=True, help_text='Escalate tier-1 accepts when rounded points after the multiplier meet or exceed this value. Leave blank to disable escalation.', null=True),
        ),
        migrations.AddField(
            model_name='contributiontype',
            name='requires_ai_review',
            field=models.BooleanField(default=False, help_text='Require AI review before tier-1 stewards can review pending submissions.'),
        ),
        migrations.AddField(
            model_name='submittedcontribution',
            name='escalated_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the active proposal was escalated to a top-level steward.', null=True),
        ),
        migrations.AlterField(
            model_name='submissionstatetransition',
            name='event',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('review', 'Steward Review'), ('bulk_reject', 'Bulk Reject'), ('gate_reject', 'AI Gate Reject'), ('edited', 'Edited by Submitter'), ('canceled', 'Canceled by Submitter'), ('appeal', 'Appeal'), ('evidence_added', 'Evidence Added'), ('escalated', 'Escalated'), ('admin', 'Admin Edit')], max_length=20),
        ),
    ]
