# Generated by Django 6.0.6 on 2026-06-16 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaderboardentry',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='badge',
            name='action',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='leaderboardentry',
            name='leaderboard',
        ),
        migrations.RemoveField(
            model_name='leaderboardentry',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
        migrations.DeleteModel(
            name='LeaderboardEntry',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
