# Generated by Django 6.0.5 on 2026-06-11 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience', models.CharField(choices=[('all', 'All users'), ('validators', 'Validators'), ('stewards', 'Stewards')], db_index=True, default='all', help_text='Only meaningful for broadcast notifications.', max_length=16)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('category', models.CharField(choices=[('submission', 'Submission'), ('contribution', 'Contribution'), ('community', 'Community'), ('content', 'Content'), ('validator', 'Validator'), ('system', 'System')], db_index=True, max_length=32)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High')], default=2)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField(blank=True)),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('link_label', models.CharField(blank=True, max_length=80)),
                ('source_app', models.CharField(blank=True, max_length=80)),
                ('source_model', models.CharField(blank=True, max_length=80)),
                ('source_object_id', models.CharField(blank=True, max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, max_length=255, null=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='Personal notifications only.', null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, help_text='Empty for broadcast notifications.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_564b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(condition=models.Q(('recipient__isnull', True)), fields=['audience', '-created_at'], name='notif_broadcast_feed_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key__isnull', False), ('recipient__isnull', False)), fields=('recipient', 'dedupe_key'), name='unique_personal_dedupe_per_recipient'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key__isnull', False), ('recipient__isnull', True)), fields=('dedupe_key',), name='unique_broadcast_dedupe'),
        ),
        migrations.AddConstraint(
            model_name='notificationreceipt',
            constraint=models.UniqueConstraint(fields=('notification', 'user'), name='unique_notification_receipt'),
        ),
    ]
