# Generated by Django 6.0.6 on 2026-06-11 17:41

import django.db.models.deletion
import notifications.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('submission', 'Submission'), ('contribution', 'Contribution'), ('community', 'Community'), ('content', 'Content'), ('validator', 'Validator'), ('system', 'System'), ('announcement', 'Announcement')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='CustomNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField(blank=True, help_text='Supports markdown on the notifications page; shown as plain text in the dropdown preview.')),
                ('link_url', models.CharField(blank=True, help_text="Optional. Internal portal path ('/missions') or full https:// URL. Leave empty for a pure announcement with no redirect.", max_length=500)),
                ('link_label', models.CharField(blank=True, max_length=80)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High')], default=2)),
                ('target_mode', models.CharField(choices=[('everyone', 'Everyone'), ('roles', 'Users with selected roles'), ('users', 'Hand-picked users'), ('wallets', 'Pasted wallet addresses')], default='everyone', max_length=16)),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('target_wallets', models.TextField(blank=True, help_text='One wallet address per line. Commas and extra whitespace are tolerated.')),
                ('channels', models.JSONField(default=notifications.models.default_channels)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], db_index=True, default='draft', max_length=12)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.PositiveIntegerField(default=0, help_text='Resolved recipients at last send.')),
                ('unmatched_wallets', models.JSONField(blank=True, default=list, help_text='Wallet lines that matched no user at last send.')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('target_users', models.ManyToManyField(blank=True, related_name='custom_notifications_targeted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'custom notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
