# Generated by Django 6.0.6 on 2026-06-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_category_customnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='audience',
            field=models.CharField(choices=[('all', 'All users'), ('validators', 'Validators'), ('stewards', 'Stewards'), ('builders', 'Builders'), ('community', 'Community members')], db_index=True, default='all', help_text='Only meaningful for broadcast notifications.', max_length=16),
        ),
    ]
