# Generated by Django 6.0.6 on 2026-06-18 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_audience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsNewAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField(blank=True)),
                ('eyebrow', models.CharField(blank=True, default="What's new", max_length=80)),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('link_label', models.CharField(blank=True, max_length=80)),
                ('image_url', models.URLField(blank=True, help_text='Cloudinary URL for the dialog image.', max_length=500)),
                ('image_public_id', models.CharField(blank=True, help_text='Cloudinary public ID for the dialog image.', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=12)),
                ('audience', models.CharField(choices=[('all', 'All users'), ('validators', 'Validators'), ('stewards', 'Stewards'), ('builders', 'Builders'), ('community', 'Community members')], db_index=True, default='all', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': "What's New announcement",
                'verbose_name_plural': "What's New announcements",
                'ordering': ['display_order', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsNewAnnouncementSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('seen', 'Seen'), ('skipped', 'Skipped'), ('opened', 'Opened link')], default='seen', max_length=16)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_records', to='notifications.whatsnewannouncement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whats_new_seen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='whatsnewannouncement',
            index=models.Index(fields=['status', 'audience', 'display_order'], name='notificatio_status_917a96_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsnewannouncement',
            index=models.Index(fields=['status', 'published_at'], name='notificatio_status_fe2037_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsnewannouncementseen',
            index=models.Index(fields=['user', 'created_at'], name='notificatio_user_id_010262_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsnewannouncementseen',
            constraint=models.UniqueConstraint(fields=('announcement', 'user', 'version'), name='unique_whats_new_seen_version'),
        ),
    ]
