# Generated by Django 6.0.3 on 2026-03-25 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_user_id', models.CharField(help_text="Platform's unique user ID", max_length=100)),
                ('platform_username', models.CharField(help_text='Username on the platform', max_length=100)),
                ('access_token', models.TextField(blank=True, help_text='Encrypted OAuth access token')),
                ('refresh_token', models.TextField(blank=True, help_text='Encrypted OAuth refresh token')),
                ('linked_at', models.DateTimeField(help_text='When the account was linked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discriminator', models.CharField(blank=True, help_text='Discord discriminator (legacy)', max_length=10)),
                ('avatar_hash', models.CharField(blank=True, help_text='Discord avatar hash for CDN URL', max_length=100)),
                ('guild_member', models.BooleanField(default=False, help_text='Whether user is in the configured Discord guild')),
                ('guild_checked_at', models.DateTimeField(blank=True, help_text='When guild membership was last checked', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discord Connection',
                'verbose_name_plural': 'Discord Connections',
                'db_table': 'social_connections_discord',
            },
        ),
        migrations.CreateModel(
            name='GitHubConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_user_id', models.CharField(help_text="Platform's unique user ID", max_length=100)),
                ('platform_username', models.CharField(help_text='Username on the platform', max_length=100)),
                ('access_token', models.TextField(blank=True, help_text='Encrypted OAuth access token')),
                ('refresh_token', models.TextField(blank=True, help_text='Encrypted OAuth refresh token')),
                ('linked_at', models.DateTimeField(help_text='When the account was linked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GitHub Connection',
                'verbose_name_plural': 'GitHub Connections',
                'db_table': 'social_connections_github',
            },
        ),
        migrations.CreateModel(
            name='TwitterConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_user_id', models.CharField(help_text="Platform's unique user ID", max_length=100)),
                ('platform_username', models.CharField(help_text='Username on the platform', max_length=100)),
                ('access_token', models.TextField(blank=True, help_text='Encrypted OAuth access token')),
                ('refresh_token', models.TextField(blank=True, help_text='Encrypted OAuth refresh token')),
                ('linked_at', models.DateTimeField(help_text='When the account was linked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Twitter Connection',
                'verbose_name_plural': 'Twitter Connections',
                'db_table': 'social_connections_twitter',
            },
        ),
        migrations.CreateModel(
            name='UsedOAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=512)),
                ('platform', models.CharField(max_length=20)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'social_connections_used_codes',
                'indexes': [models.Index(fields=['used_at'], name='social_conn_used_at_24063e_idx')],
                'unique_together': {('code', 'platform')},
            },
        ),
    ]
