# Generated by Django 6.0.5 on 2026-05-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_connections', '0002_migrate_github_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordRoleSyncLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('owner_token', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('acquired_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'social_connections_discord_role_sync_lock',
            },
        ),
        migrations.AddField(
            model_name='discordconnection',
            name='guild_joined_at',
            field=models.DateTimeField(blank=True, help_text='When the user joined the configured Discord guild', null=True),
        ),
        migrations.AddField(
            model_name='discordconnection',
            name='guild_nick',
            field=models.CharField(blank=True, help_text='Nickname in the configured Discord guild', max_length=100),
        ),
        migrations.AddField(
            model_name='discordconnection',
            name='roles_manual_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this user last manually refreshed Discord roles', null=True),
        ),
        migrations.AddField(
            model_name='discordconnection',
            name='roles_sync_error',
            field=models.TextField(blank=True, help_text='Most recent Discord role sync error, if any'),
        ),
        migrations.AddField(
            model_name='discordconnection',
            name='roles_synced_at',
            field=models.DateTimeField(blank=True, help_text='When Discord roles were last synced', null=True),
        ),
        migrations.CreateModel(
            name='DiscordRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.CharField(db_index=True, max_length=100)),
                ('role_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('color', models.PositiveIntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('hoist', models.BooleanField(default=False)),
                ('managed', models.BooleanField(default=False)),
                ('mentionable', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'social_connections_discord_role',
                'ordering': ['guild_id', '-position', 'name'],
                'indexes': [models.Index(fields=['guild_id', 'deleted_at'], name='social_conn_guild_i_189d0c_idx'), models.Index(fields=['role_id'], name='social_conn_role_id_8fa324_idx')],
                'unique_together': {('guild_id', 'role_id')},
            },
        ),
        migrations.AddField(
            model_name='discordconnection',
            name='current_roles',
            field=models.ManyToManyField(blank=True, help_text='Current roles for this user in the configured Discord guild', related_name='discord_connections', to='social_connections.discordrole'),
        ),
    ]
