# Generated by Codex on 2026-05-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_connections', '0003_discordrolesynclock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.CharField(max_length=64, unique=True)),
                ('platform', models.CharField(db_index=True, max_length=20)),
                ('code_verifier', models.TextField(blank=True)),
                ('redirect_url', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_connections_pending_oauth_state',
                'indexes': [
                    models.Index(fields=['created_at'], name='social_conn_created_28e2f1_idx'),
                    models.Index(fields=['platform', 'state_id'], name='social_conn_platfor_e73859_idx'),
                ],
            },
        ),
    ]
