# Generated by Django 6.0.6 on 2026-07-06 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_creator_audience_label'),
        ('social_connections', '0005_pendingoauthstate_session_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_user_id', models.CharField(help_text="Platform's unique user ID", max_length=100)),
                ('platform_username', models.CharField(help_text='Username on the platform', max_length=100)),
                ('access_token', models.TextField(blank=True, help_text='Encrypted OAuth access token')),
                ('refresh_token', models.TextField(blank=True, help_text='Encrypted OAuth refresh token')),
                ('linked_at', models.DateTimeField(help_text='When the account was linked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Whether portal notifications are pushed to this Telegram account (/mute toggles this)')),
                ('blocked_at', models.DateTimeField(blank=True, help_text='Set when Telegram reports the user blocked the bot; cleared on a successful re-link', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Connection',
                'verbose_name_plural': 'Telegram Connections',
                'db_table': 'social_connections_telegram',
            },
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], max_length=3)),
                ('chat_id', models.CharField(help_text="Telegram chat id at the time of the message (historical record; the drain sends to the connection's live platform_user_id)", max_length=64)),
                ('text', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='', help_text='Delivery status for outbound rows; blank for inbound rows', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='social_connections.telegramconnection')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_messages', to='notifications.notification')),
            ],
            options={
                'db_table': 'social_connections_telegram_message',
                'indexes': [models.Index(fields=['status', 'created_at'], name='social_conn_status_081b2e_idx'), models.Index(fields=['direction', '-created_at'], name='social_conn_directi_eca5f2_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('connection__isnull', False), ('direction', 'out'), ('notification__isnull', False)), fields=('notification', 'connection'), name='uniq_telegram_out_per_notification')],
            },
        ),
    ]
