# Generated by Django 6.0.6 on 2026-07-13 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_connections', '0005_pendingoauthstate_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordEarnedRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_user_id', models.CharField(db_index=True, max_length=100)),
                ('discord_username', models.CharField(blank=True, max_length=100)),
                ('role_id', models.CharField(db_index=True, max_length=100)),
                ('role_name', models.CharField(max_length=100)),
                ('total_points', models.PositiveIntegerField()),
                ('poap_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earned_role_assignments', to='social_connections.discordconnection')),
            ],
            options={
                'db_table': 'social_connections_discord_earned_role_assignment',
                'ordering': ['-created_at'],
            },
        ),
    ]
