# Generated by Django 6.0.6 on 2026-07-07 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_connections', '0005_telegramconnection_telegrammessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='telegramconnection',
            constraint=models.UniqueConstraint(fields=('platform_user_id',), name='uniq_telegram_platform_user_id'),
        ),
    ]
