# Generated by Django 6.0.6 on 2026-07-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_connections', '0006_discordearnedroleassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discordearnedroleassignment',
            options={
                'ordering': ['-created_at'],
                'permissions': (
                    (
                        'run_discord_earned_role_assignment',
                        'Can run Discord earned role assignment',
                    ),
                ),
            },
        ),
    ]
