# Generated by Django 5.2.10 on 2026-07-30 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_connections', '0007_alter_discordearnedroleassignment_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_user_id', models.CharField(help_text="Platform's unique user ID", max_length=100)),
                ('platform_username', models.CharField(help_text='Username on the platform', max_length=100)),
                ('access_token', models.TextField(blank=True, help_text='Encrypted OAuth access token')),
                ('refresh_token', models.TextField(blank=True, help_text='Encrypted OAuth refresh token')),
                ('linked_at', models.DateTimeField(help_text='When the account was linked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Connection',
                'verbose_name_plural': 'Telegram Connections',
                'db_table': 'social_connections_telegram',
            },
        ),
    ]
