# Generated by Django 6.0.6 on 2026-08-05 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_creator_audience_label'),
        ('social_connections', '0008_telegramconnection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], max_length=3)),
                ('chat_id', models.CharField(help_text="Telegram chat id at the time of the message (historical record; the drain sends to the connection's live platform_user_id)", max_length=64)),
                ('text', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='', help_text='Delivery status for outbound rows; blank for inbound rows', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'social_connections_telegram_message',
            },
        ),
        migrations.AddField(
            model_name='telegramconnection',
            name='blocked_at',
            field=models.DateTimeField(blank=True, help_text='Set when Telegram reports the user blocked the bot; cleared on a successful re-link', null=True),
        ),
        migrations.AddField(
            model_name='telegramconnection',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Whether portal notifications are pushed to this Telegram account (/mute toggles this)'),
        ),
        migrations.AddConstraint(
            model_name='telegramconnection',
            constraint=models.UniqueConstraint(fields=('platform_user_id',), name='uniq_telegram_platform_user_id'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='social_connections.telegramconnection'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_messages', to='notifications.notification'),
        ),
        migrations.AddIndex(
            model_name='telegrammessage',
            index=models.Index(fields=['status', 'created_at'], name='social_conn_status_081b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammessage',
            index=models.Index(fields=['direction', '-created_at'], name='social_conn_directi_eca5f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='telegrammessage',
            constraint=models.UniqueConstraint(condition=models.Q(('connection__isnull', False), ('direction', 'out'), ('notification__isnull', False)), fields=('notification', 'connection'), name='uniq_telegram_out_per_notification'),
        ),
    ]
