AI_REVIEW_READ_SCOPE = 'ai_review:read'
AI_REVIEW_PROPOSE_SCOPE = 'ai_review:propose'

AI_REVIEW_SCOPES = (
    AI_REVIEW_READ_SCOPE,
    AI_REVIEW_PROPOSE_SCOPE,
)

ALLOWED_SERVICE_ACCOUNT_SCOPES = frozenset(AI_REVIEW_SCOPES)
