# Generated by Django 5.2.1 on 2025-08-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validator',
            name='node_version',
            field=models.CharField(blank=True, help_text='Current node version (e.g., 0.3.9)', max_length=50, null=True),
        ),
    ]
