# Generated by Django 5.2.1 on 2025-08-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0003_create_validator_profiles_for_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='points_at_waitlist_graduation',
            field=models.IntegerField(blank=True, help_text="User's total points when they graduated from waitlist to validator", null=True),
        ),
        migrations.AddField(
            model_name='validator',
            name='waitlist_graduation_date',
            field=models.DateTimeField(blank=True, help_text='Date when user graduated from waitlist to validator', null=True),
        ),
    ]
