# Generated by Django 5.2.1

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0004_add_waitlist_graduation_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validator',
            name='waitlist_graduation_date',
        ),
    ]