# Generated by Django 5.2.5 on 2025-08-22 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0005_remove_waitlist_graduation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validator',
            name='points_at_waitlist_graduation',
        ),
    ]
