# Generated by Django 5.2.1 on 2025-11-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0006_remove_graduation_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatorWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(db_index=True, max_length=42, unique=True)),
                ('operator_address', models.CharField(db_index=True, max_length=42)),
                ('status', models.CharField(choices=[('active', 'Active'), ('quarantined', 'Quarantined'), ('banned', 'Banned'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('moniker', models.CharField(blank=True, max_length=255)),
                ('logo_uri', models.URLField(blank=True, max_length=500)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('v_stake', models.CharField(blank=True, max_length=78)),
                ('d_stake', models.CharField(blank=True, max_length=78)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validator_wallets', to='validators.validator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
