# Generated by Django 5.2.1 on 2025-12-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0007_validatorwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validatorwallet',
            name='operator_address',
            field=models.CharField(blank=True, db_index=True, default='', max_length=42),
        ),
    ]
