# Generated by Django 6.0.3 on 2026-03-08 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0007_validatorwallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatorWalletStatusSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('quarantined', 'Quarantined'), ('banned', 'Banned'), ('inactive', 'Inactive')], max_length=20)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='validatorwallet',
            name='network',
            field=models.CharField(choices=[('asimov', 'Asimov'), ('bradbury', 'Bradbury')], db_index=True, default='asimov', max_length=20),
        ),
        migrations.AlterField(
            model_name='validatorwallet',
            name='address',
            field=models.CharField(db_index=True, max_length=42),
        ),
        migrations.AddConstraint(
            model_name='validatorwallet',
            constraint=models.UniqueConstraint(fields=('address', 'network'), name='unique_wallet_per_network'),
        ),
        migrations.AddField(
            model_name='validatorwalletstatussnapshot',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_snapshots', to='validators.validatorwallet'),
        ),
        migrations.AddConstraint(
            model_name='validatorwalletstatussnapshot',
            constraint=models.UniqueConstraint(fields=('wallet', 'date'), name='unique_snapshot_per_wallet_date'),
        ),
    ]
