# Generated by Django 6.0.3 on 2026-03-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0008_validatorwalletstatussnapshot_and_more'),
    ]

    operations = [
        # Rename existing node_version to node_version_asimov (preserves data)
        migrations.RenameField(
            model_name='validator',
            old_name='node_version',
            new_name='node_version_asimov',
        ),
        migrations.AlterField(
            model_name='validator',
            name='node_version_asimov',
            field=models.CharField(blank=True, help_text='Current node version for Asimov network (e.g., 0.3.9)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='validator',
            name='node_version_bradbury',
            field=models.CharField(blank=True, help_text='Current node version for Bradbury network (e.g., 0.3.9)', max_length=50, null=True),
        ),
    ]
