# Generated by Django 6.0.5 on 2026-05-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0011_validator_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatorwallet',
            name='last_grafana_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validatorwallet',
            name='logs_status',
            field=models.CharField(choices=[('on', 'On'), ('shame', 'Shame'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='validatorwallet',
            name='metrics_status',
            field=models.CharField(choices=[('on', 'On'), ('shame', 'Shame'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=10),
        ),
    ]
