# Generated by Django 6.0.6 on 2026-06-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0013_validatorwallet_shame_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatorwallet',
            name='assets_under_management_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Assets under management in USD, shown on the overview (e.g. 42600000 → $42.6M).', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='validatorwallet',
            name='overview_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the overview validators panel.'),
        ),
        migrations.AddField(
            model_name='validatorwallet',
            name='show_in_overview',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
