# Generated by Django 6.0.6 on 2026-07-01 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0014_validatorwallet_assets_under_management_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatorwalletstatussnapshot',
            name='logs_samples',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='validatorwalletstatussnapshot',
            name='logs_status',
            field=models.CharField(choices=[('on', 'On'), ('shame', 'Shame'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='validatorwalletstatussnapshot',
            name='metrics_samples',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='validatorwalletstatussnapshot',
            name='metrics_status',
            field=models.CharField(choices=[('on', 'On'), ('shame', 'Shame'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='validatorwalletstatussnapshot',
            name='node_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='validatorwalletstatussnapshot',
            name='version_status',
            field=models.CharField(choices=[('on', 'On'), ('warning', 'Warning'), ('shame', 'Shame'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.CreateModel(
            name='ValidatorWalletObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('onchain_status', models.CharField(choices=[('active', 'Active'), ('quarantined', 'Quarantined'), ('banned', 'Banned'), ('inactive', 'Inactive')], max_length=20)),
                ('metrics_status', models.CharField(choices=[('on', 'On'), ('shame', 'Shame'), ('unknown', 'Unknown')], max_length=10)),
                ('logs_status', models.CharField(choices=[('on', 'On'), ('shame', 'Shame'), ('unknown', 'Unknown')], max_length=10)),
                ('version_status', models.CharField(choices=[('on', 'On'), ('warning', 'Warning'), ('shame', 'Shame'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('node_version', models.CharField(blank=True, max_length=50)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='validators.validatorwallet')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['wallet', 'observed_at'], name='validators__wallet__8b42c1_idx')],
            },
        ),
    ]
