# Generated by Django 5.2.1 on 2025-05-22 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributiontypemultiplier',
            options={},
        ),
        migrations.RemoveField(
            model_name='contributiontypemultiplier',
            name='is_active',
        ),
        migrations.CreateModel(
            name='MultiplierPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('multiplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='leaderboard.contributiontypemultiplier')),
            ],
            options={
                'ordering': ['-valid_from'],
                'get_latest_by': 'valid_from',
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='valid_until_after_valid_from')],
            },
        ),
    ]
