# Generated by Django 5.2.1 on 2025-05-22 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_contribution_contribution_date_and_more'),
        ('leaderboard', '0004_remove_multiplierperiod_valid_until_after_valid_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplierperiod',
            name='multiplier',
        ),
        migrations.CreateModel(
            name='GlobalLeaderboardMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('multiplier_value', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('valid_from', models.DateTimeField()),
                ('description', models.CharField(blank=True, help_text='Reason for this multiplier value', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('contribution_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multipliers', to='contributions.contributiontype')),
            ],
            options={
                'ordering': ['-valid_from'],
                'get_latest_by': 'valid_from',
            },
        ),
        migrations.DeleteModel(
            name='ContributionTypeMultiplier',
        ),
        migrations.DeleteModel(
            name='MultiplierPeriod',
        ),
    ]
