# Generated by Django 5.2.1 on 2025-05-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_remove_multiplierperiod_multiplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalleaderboardmultiplier',
            name='multiplier_value',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
