# Generated by Django 5.2.1 on 2025-08-15 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0013_category_contributiontype_category'),
        ('leaderboard', '0006_alter_globalleaderboardmultiplier_multiplier_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='contributions.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_leaderboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category Leaderboard Entry',
                'verbose_name_plural': 'Category Leaderboard Entries',
                'ordering': ['-total_points', 'user__name'],
                'unique_together': {('user', 'category')},
            },
        ),
    ]
