# Generated by Django 5.2.1 on 2025-08-15 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0014_setup_initial_categories'),
        ('leaderboard', '0007_categoryleaderboard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Null for global leaderboard, or specific category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='contributions.category'),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='leaderboardentry',
            unique_together={('user', 'category')},
        ),
        migrations.DeleteModel(
            name='CategoryLeaderboard',
        ),
    ]
