# Generated by Django 5.1.2 on 2024-08-16

from django.db import migrations
from django.utils import timezone


def add_journey_multipliers(apps, schema_editor):
    GlobalLeaderboardMultiplier = apps.get_model('leaderboard', 'GlobalLeaderboardMultiplier')
    ContributionType = apps.get_model('contributions', 'ContributionType')
    
    # Get the journey contribution types
    try:
        validator_waitlist = ContributionType.objects.get(slug='validator-waitlist')
        builder_initiate = ContributionType.objects.get(slug='builder-initiate')
        
        # Create multipliers for journey types (1.0 multiplier - points are already set at 20)
        GlobalLeaderboardMultiplier.objects.get_or_create(
            contribution_type=validator_waitlist,
            valid_from=timezone.now(),
            defaults={
                'multiplier_value': 1.0,
                'description': 'Initial multiplier for validator waitlist badge',
                'notes': 'Award 20 points for completing validator journey'
            }
        )
        
        GlobalLeaderboardMultiplier.objects.get_or_create(
            contribution_type=builder_initiate,
            valid_from=timezone.now(),
            defaults={
                'multiplier_value': 1.0,
                'description': 'Initial multiplier for builder initiate badge',
                'notes': 'Award 20 points for completing builder journey'
            }
        )
        
        print("Journey multipliers added successfully")
        
    except ContributionType.DoesNotExist:
        print("Journey contribution types not found. Please run contributions migration first.")


def remove_journey_multipliers(apps, schema_editor):
    GlobalLeaderboardMultiplier = apps.get_model('leaderboard', 'GlobalLeaderboardMultiplier')
    ContributionType = apps.get_model('contributions', 'ContributionType')
    
    try:
        validator_waitlist = ContributionType.objects.get(slug='validator-waitlist')
        builder_initiate = ContributionType.objects.get(slug='builder-initiate')
        
        GlobalLeaderboardMultiplier.objects.filter(
            contribution_type__in=[validator_waitlist, builder_initiate]
        ).delete()
        
    except ContributionType.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0008_leaderboardentry_category_and_more'),
        ('contributions', '0017_add_journey_contribution_types'),
    ]

    operations = [
        migrations.RunPython(add_journey_multipliers, remove_journey_multipliers),
    ]