# Generated by Django 5.2.1 on 2025-08-20 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0018_rename_builder_initiate_to_welcome'),
        ('leaderboard', '0009_add_journey_multipliers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaderboardentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='leaderboard_type',
            field=models.CharField(blank=True, choices=[('validator', 'Validator'), ('builder', 'Builder'), ('validator-waitlist', 'Validator Waitlist')], help_text='Type of leaderboard this entry belongs to', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='category',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED - use leaderboard_type instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_leaderboard_entries', to='contributions.category'),
        ),
        migrations.AlterUniqueTogether(
            name='leaderboardentry',
            unique_together={('user', 'leaderboard_type')},
        ),
    ]
