# Generated by Django 5.2.1

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0011_migrate_to_leaderboard_types'),
    ]

    operations = [
        # Rename the field from leaderboard_type to type at the model level
        # but keep the same db_column name to avoid database changes
        migrations.RenameField(
            model_name='leaderboardentry',
            old_name='leaderboard_type',
            new_name='type',
        ),
        # Update the field to use db_column to keep the same database column name
        migrations.AlterField(
            model_name='leaderboardentry',
            name='type',
            field=models.CharField(
                max_length=50,
                choices=[('validator', 'Validator'), ('builder', 'Builder'), ('validator-waitlist', 'Validator Waitlist')],
                db_column='leaderboard_type',
                help_text="Type of leaderboard this entry belongs to"
            ),
        ),
        # Update unique_together to use the new field name
        migrations.AlterUniqueTogether(
            name='leaderboardentry',
            unique_together={('user', 'type')},
        ),
        # Remove the deprecated category field
        migrations.RemoveField(
            model_name='leaderboardentry',
            name='category',
        ),
    ]