# Generated by Django 5.2.5 on 2025-08-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0012_finalize_leaderboard_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='graduation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='type',
            field=models.CharField(choices=[('validator', 'Validator'), ('builder', 'Builder'), ('validator-waitlist', 'Validator Waitlist'), ('validator-waitlist-graduation', 'Validator Waitlist Graduation')], help_text='Type of leaderboard this entry belongs to', max_length=50),
        ),
    ]
