# Generated by Django 5.2.7 on 2025-10-06 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0013_unified_leaderboard_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('builder_points', models.PositiveIntegerField(default=0, help_text="10% of referred users' builder contributions")),
                ('validator_points', models.PositiveIntegerField(default=0, help_text="10% of referred users' validator contributions")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Points',
                'verbose_name_plural': 'Referral Points',
            },
        ),
    ]
