# Generated by Django 6.0.6 on 2026-07-04 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0014_add_referral_points_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['type', 'rank'], name='leaderboard_type_rank_idx'),
        ),
    ]
