# Generated by Django 5.2.7 on 2026-01-30 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(blank=True, help_text='Platform username', max_length=100)),
                ('platform_user_id', models.CharField(blank=True, help_text='Platform user ID for unique identification', max_length=50)),
                ('access_token', models.TextField(blank=True, help_text='Encrypted access token')),
                ('refresh_token', models.TextField(blank=True, help_text='Encrypted refresh token (if applicable)')),
                ('linked_at', models.DateTimeField(blank=True, help_text='When the account was linked', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GitHub Connection',
                'verbose_name_plural': 'GitHub Connections',
            },
        ),
    ]
