# Generated by Django 5.2.7 on 2026-01-30

from django.db import migrations


def migrate_github_data(apps, schema_editor):
    """
    Migrate GitHub OAuth data from User model to GitHubConnection model.

    This migration handles the case where the User model may or may not have
    the old GitHub fields (github_user_id, github_username, etc.) depending
    on whether this is a fresh database or an existing one.
    """
    User = apps.get_model('users', 'User')
    GitHubConnection = apps.get_model('social_github', 'GitHubConnection')

    # Check if the User model has the old GitHub fields
    # In a fresh database (like during tests), these fields won't exist
    user_fields = [f.name for f in User._meta.get_fields()]

    if 'github_user_id' not in user_fields:
        # Fresh database - no data to migrate
        print("No GitHub fields on User model - skipping migration")
        return

    # Find users with GitHub data
    users_with_github = User.objects.exclude(github_user_id='').exclude(github_user_id__isnull=True)

    count = 0
    for user in users_with_github:
        # Create GitHubConnection if it doesn't already exist
        _, created = GitHubConnection.objects.get_or_create(
            user=user,
            defaults={
                'username': user.github_username or '',
                'platform_user_id': user.github_user_id or '',
                'access_token': user.github_access_token or '',
                'linked_at': user.github_linked_at
            }
        )
        if created:
            count += 1

    print(f"Migrated {count} GitHub connections")


def reverse_migrate_github_data(apps, schema_editor):
    """
    Reverse migration: copy data back to User model.
    Note: This is mainly for safety; the User fields will be removed later.
    """
    User = apps.get_model('users', 'User')
    GitHubConnection = apps.get_model('social_github', 'GitHubConnection')

    # Check if the User model has the old GitHub fields
    user_fields = [f.name for f in User._meta.get_fields()]

    if 'github_user_id' not in user_fields:
        # Can't reverse to fields that don't exist
        print("No GitHub fields on User model - skipping reverse migration")
        return

    for connection in GitHubConnection.objects.all():
        user = connection.user
        user.github_username = connection.username
        user.github_user_id = connection.platform_user_id
        user.github_access_token = connection.access_token
        user.github_linked_at = connection.linked_at
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('social_github', '0001_initial'),
        ('users', '0001_initial'),  # Ensure users migration has run
    ]

    operations = [
        migrations.RunPython(migrate_github_data, reverse_migrate_github_data),
    ]
