# Generated by Django 6.0.6 on 2026-07-29 11:09

import campaigns.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_id', models.CharField(default=campaigns.models.generate_tracking_id, editable=False, help_text='Server-generated opaque ID published as utm_id. Immutable.', max_length=20, unique=True)),
                ('role', models.CharField(choices=[('builder', 'Builder'), ('validator', 'Validator'), ('community', 'Community')], max_length=16)),
                ('alias', models.CharField(help_text='URL segment after the role, e.g. "ethcc" for /join/builders/ethcc.', max_length=64, validators=[django.core.validators.RegexValidator('^[a-z0-9-]+$', 'Use only lowercase letters, digits, and hyphens.')])),
                ('destination_path', models.CharField(help_text='Relative portal path the link redirects to, e.g. /builders.', max_length=200)),
                ('utm_source', models.CharField(help_text='e.g. x, discord, newsletter, ethcc', max_length=64)),
                ('utm_medium', models.CharField(help_text='e.g. organic_social, paid_social, email, event', max_length=64)),
                ('utm_content', models.CharField(blank=True, help_text='Optional creative ID, e.g. launch_post_01', max_length=64)),
                ('utm_term', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True, help_text='Prefer pausing over deleting.')),
                ('starts_at', models.DateTimeField(blank=True, help_text='Optional override of the campaign window.', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Optional override of the campaign window.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRedirectHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('referrer_host', models.CharField(blank=True, max_length=100)),
                ('user_agent_family', models.CharField(blank=True, max_length=32)),
                ('device_category', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('is_probable_bot', models.BooleanField(default=False)),
                ('campaign_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='campaigns.campaignlink')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('tracking_key', models.CharField(help_text='Published as utm_campaign, e.g. ethcc_role_recruitment. Immutable once links are live; clone the campaign instead of changing its meaning.', max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+$', 'Use only lowercase letters, digits, and underscores.')])),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Prefer deactivating over deleting.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='campaignlink',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='campaigns.marketingcampaign'),
        ),
        migrations.CreateModel(
            name='UserAcquisitionAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link_tracking_id', models.CharField(max_length=20)),
                ('campaign_key', models.CharField(max_length=64)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('medium', models.CharField(blank=True, max_length=64)),
                ('content', models.CharField(blank=True, max_length=64)),
                ('term', models.CharField(blank=True, max_length=64)),
                ('link_role', models.CharField(blank=True, max_length=16)),
                ('landing_path', models.CharField(blank=True, max_length=200)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField()),
                ('campaign_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquisitions', to='campaigns.campaignlink')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acquisition_attribution', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='campaignlink',
            constraint=models.UniqueConstraint(fields=('role', 'alias'), name='unique_campaign_link_role_alias'),
        ),
    ]
