# Generated by Django 5.2.5 on 2025-08-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_upgrade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetnodeversion',
            name='target_date',
            field=models.DateTimeField(help_text='Date when this version becomes available for upgrade (used for early upgrade bonus calculation)'),
        ),
    ]
