# Generated by Django 6.0.3 on 2026-03-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_upgrade', '0002_update_target_date_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetnodeversion',
            name='network',
            field=models.CharField(choices=[('asimov', 'Asimov'), ('bradbury', 'Bradbury')], default='asimov', help_text='Which network this target version applies to', max_length=20),
        ),
        migrations.AlterField(
            model_name='targetnodeversion',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one target can be active at a time per network'),
        ),
    ]
