# Generated by Django 6.0.6 on 2026-06-12 14:52

from django.db import migrations, models

# Original points of the tasks seeded by 0001_initial, used to reverse.
SEEDED_POINTS = {
    'follow-genlayer-x': 10,
    'join-genlayer-discord': 10,
    'check-out-genlayer-on-x': 5,
}


def set_existing_tasks_to_500_points(apps, schema_editor):
    """Bump every existing task to the new 500-point default.

    Completions keep their frozen points_awarded snapshot by design; only
    future completions earn the new value.
    """
    SocialTask = apps.get_model('social_tasks', 'SocialTask')
    SocialTask.objects.exclude(points=500).update(points=500)


def restore_seeded_task_points(apps, schema_editor):
    """Restore the known seeded values; admin-created tasks keep 500."""
    SocialTask = apps.get_model('social_tasks', 'SocialTask')
    for slug, points in SEEDED_POINTS.items():
        SocialTask.objects.filter(slug=slug).update(points=points)


class Migration(migrations.Migration):

    dependencies = [
        ('social_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialtask',
            name='points',
            field=models.PositiveIntegerField(default=500, help_text='Points awarded on completion. Frozen as points_awarded on each completion row.'),
        ),
        migrations.RunPython(set_existing_tasks_to_500_points, restore_seeded_task_points),
    ]
