# Generated by Django 6.0.6 on 2026-07-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_tasks', '0006_backfill_builder_star_completions'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialtask',
            name='counts_as_activation',
            field=models.BooleanField(default=False, help_text='Completions count as community activation in campaign reporting.'),
        ),
    ]
