# Generated by Django 6.0.5 on 2026-05-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_tv', '0003_upsert_fud_markets_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='image_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for thumbnail / cover image.', max_length=255),
        ),
        migrations.AlterField(
            model_name='stream',
            name='image_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for thumbnail / cover image.', max_length=500),
        ),
    ]
