# Generated by Django 6.0.5 on 2026-05-20 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_tv', '0004_stream_image_public_id_alter_stream_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('group', models.CharField(choices=[('internal', 'Internal team'), ('community', 'Community')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'stream category',
                'verbose_name_plural': 'stream categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='stream',
            name='category',
            field=models.CharField(choices=[('internal', 'Internal team'), ('community', 'Community')], max_length=20),
        ),
        migrations.AddField(
            model_name='stream',
            name='detailed_category',
            field=models.ForeignKey(blank=True, help_text='Optional detailed category for filtering Gen TV.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streams', to='gen_tv.streamcategory'),
        ),
    ]
