# Generated by Django 6.0.5 on 2026-05-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='logo_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for partner logo.', max_length=255),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for partner logo.', max_length=500),
        ),
    ]
