# Generated by Django 6.0.6 on 2026-06-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partner_logo_public_id_alter_partner_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='show_in_overview',
            field=models.BooleanField(db_index=True, default=True, help_text='Show this partner in the overview page logo marquee. Untick to hide it there.'),
        ),
    ]
