# Generated by Django 6.0.6 on 2026-06-19

from django.db import migrations, models


def copy_logo_to_overview_logo(apps, schema_editor):
    Partner = apps.get_model('partners', 'Partner')
    Partner.objects.filter(
        show_in_overview=True,
        overview_logo_url='',
        logo_url__gt='',
    ).update(overview_logo_url=models.F('logo_url'))


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_partner_show_in_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='overview_logo_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for the partner logo used in the overview marquee.', max_length=500),
        ),
        migrations.AddField(
            model_name='partner',
            name='overview_logo_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for the overview marquee logo.', max_length=255),
        ),
        migrations.RunPython(copy_logo_to_overview_logo, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='partner',
            name='show_in_overview',
            field=models.BooleanField(db_index=True, default=False, help_text='Show this partner in the overview page logo marquee. Untick to hide it there.'),
        ),
    ]
