"""
Django settings for tally project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def get_required_env(key):
    """Get required environment variable or raise error if not found."""
    value = os.environ.get(key)
    if value is None:
        raise ValueError(f"Required environment variable '{key}' is not set")
    return value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_required_env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
_debug_raw = get_required_env('DEBUG')
DEBUG = _debug_raw.lower() == 'true'
print(f"[STARTUP] DEBUG={DEBUG} (raw: {repr(_debug_raw)})")

ALLOWED_HOSTS = get_required_env('ALLOWED_HOSTS').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_yasg',
    'django_filters',
    'django_recaptcha',
    'allow_cidr',
    
    # Local apps
    'api',
    'utils',
    'users',
    'contributions',
    'contributions.node_upgrade',
    'projects',
    'leaderboard',
    'ethereum_auth',
    'validators',
    'builders',
    'stewards',
    'creators',
    'partners',
    'gen_tv',
    'social_connections',
    'community_xp.apps.CommunityXpConfig',
    'poaps.apps.PoapsConfig',
    'social_tasks',
    'notifications.apps.NotificationsConfig',
    'service_accounts',
]

MIDDLEWARE = [
    'tally.middleware.APILoggingMiddleware',  # Request logging (must be first for timing)
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'allow_cidr.middleware.AllowCIDRMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'tally.middleware.DBLoggingMiddleware',  # DB query logging (must be last)
]

ROOT_URLCONF = 'tally.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tally.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    # Production database (RDS)
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
else:
    # Development database (SQLite)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (User-uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'ethereum_auth.authentication.EthereumAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_PAGINATION_CLASS': 'utils.pagination.SafePageNumberPagination',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'poap_claim_secret': '10/minute',
        # SIWE nonce/login are unauthenticated: bound per-IP brute force
        'siwe_auth': '30/minute',
        # Public profile/search surfaces: allow normal browsing, bound scraping
        'public_user_search': '30/minute',
        'public_user_profile': '60/minute',
        # Anonymous-only (see LeaderboardViewSet.get_throttles); payloads are
        # already address-truncated, this just slows bulk scraping.
        'public_leaderboard': '300/minute',
        # Wallet linking is a one-time action per validator
        'wallet_link': '10/hour',
        'pending_email_start': '10/hour',
        'pending_email_resend': '10/hour',
        'pending_email_confirm': '30/hour',
        'existing_email_start': '10/hour',
        'existing_email_resend': '10/hour',
        'existing_email_confirm': '30/hour',
    },
    'PAGE_SIZE': 10,
}

# JWT settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
    'ROTATE_REFRESH_TOKENS': True,
    # Rotated refresh tokens are blacklisted so a stolen refresh token can't
    # keep minting new sessions after its replacement is issued.
    'BLACKLIST_AFTER_ROTATION': True,
}

# CORS settings
if DEBUG:
    # Even in development, never reflect arbitrary origins with credentials:
    # a malicious website could otherwise make authenticated requests against
    # a dev backend (which often holds prod-derived data). Local frontends run
    # on varying ports, so allow any localhost port instead of allow-all.
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r'^http://localhost(:\d+)?$',
        r'^http://127\.0\.0\.1(:\d+)?$',
    ]
else:
    CORS_ALLOWED_ORIGINS = get_required_env('CORS_ALLOWED_ORIGINS').split(',')
CORS_ALLOW_CREDENTIALS = True

# Cloudinary settings
CLOUDINARY_CLOUD_NAME = os.environ.get('CLOUDINARY_CLOUD_NAME', '')
CLOUDINARY_API_KEY = os.environ.get('CLOUDINARY_API_KEY', '')
CLOUDINARY_API_SECRET = os.environ.get('CLOUDINARY_API_SECRET', '')
CLOUDINARY_UPLOAD_PRESET = os.environ.get('CLOUDINARY_UPLOAD_PRESET', 'tally_unsigned')  # For browser uploads

# Backend URL (for constructing OAuth redirect URIs)
BACKEND_URL = os.environ.get('BACKEND_URL', 'http://localhost:8000').strip().rstrip('/')

# GitHub OAuth settings
GITHUB_CLIENT_ID = os.environ.get('GITHUB_CLIENT_ID', '')
GITHUB_CLIENT_SECRET = os.environ.get('GITHUB_CLIENT_SECRET', '')
# Auto-calculate redirect URI from backend URL
GITHUB_REDIRECT_URI = f"{BACKEND_URL}/api/auth/github/callback/"
GITHUB_ENCRYPTION_KEY = os.environ.get('GITHUB_ENCRYPTION_KEY', '')
GITHUB_REPO_TO_STAR = os.environ.get('GITHUB_REPO_TO_STAR', 'genlayerlabs/genlayer-project-boilerplate')
# Slug of the social task that gates the (point-free) builder role grant. Keep in
# sync with the seed in social_tasks migration 0004; renaming/deactivating that
# task blocks builder completion until it's restored.
BUILDER_JOURNEY_TASK_SLUG = os.environ.get('BUILDER_JOURNEY_TASK_SLUG', 'star-genlayer-boilerplate')

# Twitter/X OAuth settings
TWITTER_CLIENT_ID = os.environ.get('TWITTER_CLIENT_ID', '')
TWITTER_CLIENT_SECRET = os.environ.get('TWITTER_CLIENT_SECRET', '')
TWITTER_REDIRECT_URI = os.environ.get('TWITTER_REDIRECT_URI', f"{BACKEND_URL}/api/auth/twitter/callback/")
X_METRICS_USERNAME = os.environ.get('X_METRICS_USERNAME', 'GenLayer')
# Handle the community-journey X post must @mention (without @). Used to verify
# the post tags GenLayer.
GENLAYER_X_HANDLE = os.environ.get('GENLAYER_X_HANDLE', 'genlayer')

# Discord OAuth settings
DISCORD_CLIENT_ID = os.environ.get('DISCORD_CLIENT_ID', '')
DISCORD_CLIENT_SECRET = os.environ.get('DISCORD_CLIENT_SECRET', '')
DISCORD_REDIRECT_URI = os.environ.get('DISCORD_REDIRECT_URI', f"{BACKEND_URL}/api/auth/discord/callback/")
DISCORD_GUILD_ID = os.environ.get('DISCORD_GUILD_ID', '')
DISCORD_BOT_TOKEN = os.environ.get('DISCORD_BOT_TOKEN', '')
DISCORD_ROLE_SYNC_BATCH_SIZE = int(os.environ.get('DISCORD_ROLE_SYNC_BATCH_SIZE', '500'))
DISCORD_MANUAL_ROLE_SYNC_COOLDOWN_SECONDS = int(
    os.environ.get('DISCORD_MANUAL_ROLE_SYNC_COOLDOWN_SECONDS', '30')
)
DISCORD_ROLE_SUBMISSION_SYNC_GRACE_SECONDS = int(
    os.environ.get('DISCORD_ROLE_SUBMISSION_SYNC_GRACE_SECONDS', '30')
)
# Earned community role automation (Synapse/Brain). All three role IDs must be
# set or the assignment job is a no-op.
DISCORD_SYNAPSE_ROLE_ID = os.environ.get('DISCORD_SYNAPSE_ROLE_ID', '')
DISCORD_BRAIN_ROLE_ID = os.environ.get('DISCORD_BRAIN_ROLE_ID', '')
DISCORD_NEUROCREATIVE_ROLE_ID = os.environ.get('DISCORD_NEUROCREATIVE_ROLE_ID', '')

# Investor overview metrics
GITHUB_METRICS_REPO = os.environ.get('GITHUB_METRICS_REPO', GITHUB_REPO_TO_STAR)
GITHUB_METRICS_TOKEN = os.environ.get('GITHUB_METRICS_TOKEN', '')
DEFILLAMA_FEES_RANK = os.environ.get('DEFILLAMA_FEES_RANK', '')
DEFILLAMA_FEES_RANK_URL = os.environ.get('DEFILLAMA_FEES_RANK_URL', 'https://defillama.com/fees/chains')
OVERVIEW_TOP_VALIDATORS = os.environ.get('OVERVIEW_TOP_VALIDATORS', '')
# Telegram members: a bot reads the live count when both are set, else fall back to a curated number.
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_CHAT_ID = os.environ.get('TELEGRAM_CHAT_ID', '')
TELEGRAM_MEMBERS = os.environ.get('TELEGRAM_MEMBERS', '')
# GenLayer Studio executive metrics dashboard (decisions/chain-tx time series for the overview chart).
STUDIO_METRICS_URL = os.environ.get('STUDIO_METRICS_URL', 'https://studio-metrics-dashboard.vercel.app/api/metrics/executive')

# Shared social connection encryption key (falls back to GitHub key for backward compat)
SOCIAL_ENCRYPTION_KEY = os.environ.get('SOCIAL_ENCRYPTION_KEY', '') or GITHUB_ENCRYPTION_KEY

# Sorsa (Twitter / X social verification provider) settings.
# Only the secret + base URL come from env. Path and timeout live as code
# constants in social_tasks/sorsa_client.py next to the response parser.
SORSA_API_BASE_URL = os.environ.get('SORSA_API_BASE_URL', 'https://api.sorsa.io/v3').strip().rstrip('/')
SORSA_API_KEY = os.environ.get('SORSA_API_KEY', '')

# Frontend URL for OAuth redirects
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173').strip().rstrip('/')

# Email verification delivery and bot protection.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'email-smtp.us-east-1.amazonaws.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587') or '587')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@example.com')

TURNSTILE_SITE_KEY = os.environ.get('TURNSTILE_SITE_KEY', '')
TURNSTILE_SECRET_KEY = os.environ.get('TURNSTILE_SECRET_KEY', '')
TURNSTILE_ALLOWED_HOSTNAMES = [
    host.strip()
    for host in os.environ.get('TURNSTILE_ALLOWED_HOSTNAMES', '').split(',')
    if host.strip()
]

EMAIL_VERIFICATION_TOKEN_TTL_SECONDS = int(os.environ.get('EMAIL_VERIFICATION_TOKEN_TTL_SECONDS', '1800') or '1800')
EMAIL_VERIFICATION_MAX_ATTEMPTS = int(os.environ.get('EMAIL_VERIFICATION_MAX_ATTEMPTS', '5') or '5')
EMAIL_VERIFICATION_RESEND_COOLDOWN_SECONDS = int(os.environ.get('EMAIL_VERIFICATION_RESEND_COOLDOWN_SECONDS', '60') or '60')
PENDING_WALLET_SIGNUP_TTL_SECONDS = int(os.environ.get('PENDING_WALLET_SIGNUP_TTL_SECONDS', '1800') or '1800')
EMAIL_VERIFICATION_HMAC_KEY = os.environ.get('EMAIL_VERIFICATION_HMAC_KEY', SECRET_KEY)
EMAIL_VERIFICATION_ENCRYPTION_KEY = os.environ.get('EMAIL_VERIFICATION_ENCRYPTION_KEY', '')


# CSRF settings
CSRF_TRUSTED_ORIGINS = get_required_env('CSRF_TRUSTED_ORIGINS').split(',')
if DEBUG:
    # Local frontend ports vary across Vite, Conductor, and ad-hoc preview
    # servers. The Vite dev proxy normalizes Origin for /api requests, and
    # these entries cover the common direct-backend cases during development.
    CSRF_TRUSTED_ORIGINS = list(dict.fromkeys([
        *CSRF_TRUSTED_ORIGINS,
        FRONTEND_URL,
        'http://localhost:5173',
        'http://127.0.0.1:5173',
        'http://localhost:55010',
        'http://127.0.0.1:55010',
    ]))

# Session settings
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'  # 'None' if using cross-site cookies, but requires HTTPS
SESSION_COOKIE_AGE = 86400 * 14  # 14 days in seconds
SESSION_COOKIE_DOMAIN = None  # Allow cookies on localhost
SESSION_SAVE_EVERY_REQUEST = False  # Avoid writing unchanged sessions on every authenticated request

# Only send the session/CSRF cookies over HTTPS in production. In DEBUG the
# dev server runs over plain HTTP, so keep these off locally.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# Dynamic session cookie name based on port to prevent conflicts in multi-port development
# This allows running multiple instances on different ports without session conflicts
import sys

# Function to extract port from command line
def get_port_from_argv():
    """Extract port number from runserver command arguments"""
    if 'runserver' in sys.argv:
        try:
            # Find the runserver argument
            runserver_index = sys.argv.index('runserver')
            if runserver_index + 1 < len(sys.argv):
                server_arg = sys.argv[runserver_index + 1]
                # Handle both '8000' and '0.0.0.0:8000' formats
                if ':' in server_arg:
                    return server_arg.split(':')[-1]
                elif server_arg.isdigit():
                    return server_arg
        except (ValueError, IndexError):
            pass
    return '8000'  # Default port

# Set cookie names based on port for development
if DEBUG and 'runserver' in sys.argv:
    port = get_port_from_argv()
    SESSION_COOKIE_NAME = f'tally_sessionid_{port}'
    CSRF_COOKIE_NAME = f'tally_csrftoken_{port}'
    # Port-specific cookies configured for development
else:
    # Production settings
    SESSION_COOKIE_NAME = 'tally_sessionid'
    CSRF_COOKIE_NAME = 'csrftoken'

# Ethereum authentication settings
ETHEREUM_AUTH = {
    'SIWE_DOMAIN': get_required_env('SIWE_DOMAIN'),
    'NONCE_EXPIRY_MINUTES': 5,
}

# Custom user model
AUTH_USER_MODEL = 'users.User'

# Blockchain settings
# Shared RPC URL for all networks
VALIDATOR_RPC_URL = get_required_env('VALIDATOR_RPC_URL')

# Legacy settings (backward compatibility - deprecated, use TESTNET_NETWORKS instead)
VALIDATOR_CONTRACT_ADDRESS = os.environ.get(
    'ASIMOV_STAKING_CONTRACT_ADDRESS',
    os.environ.get('VALIDATOR_CONTRACT_ADDRESS', '')
)
FACTORY_CONTRACT_ADDRESS = os.environ.get(
    'ASIMOV_FACTORY_CONTRACT_ADDRESS',
    os.environ.get('FACTORY_CONTRACT_ADDRESS', '')
)

# Multi-network configuration
TESTNET_NETWORKS = {
    'asimov': {
        'name': 'Asimov',
        'rpc_url': os.environ.get('ASIMOV_RPC_URL', VALIDATOR_RPC_URL),
        'staking_contract_address': os.environ.get(
            'ASIMOV_STAKING_CONTRACT_ADDRESS',
            os.environ.get('VALIDATOR_CONTRACT_ADDRESS', '')
        ),
        'factory_contract_address': os.environ.get(
            'ASIMOV_FACTORY_CONTRACT_ADDRESS',
            os.environ.get('FACTORY_CONTRACT_ADDRESS', '')
        ),
        'explorer_url': os.environ.get('ASIMOV_EXPLORER_URL', 'https://explorer.testnet-chain.genlayer.com'),
    },
    'bradbury': {
        'name': 'Bradbury',
        'rpc_url': os.environ.get('BRADBURY_RPC_URL', VALIDATOR_RPC_URL),
        'staking_contract_address': os.environ.get('BRADBURY_STAKING_CONTRACT_ADDRESS', ''),
        'factory_contract_address': os.environ.get('BRADBURY_FACTORY_CONTRACT_ADDRESS', ''),
        'explorer_url': os.environ.get('BRADBURY_EXPLORER_URL', ''),
    },
}

# Uptime lookback window (days) - how many days back to check for active status
UPTIME_LOOKBACK_DAYS = int(os.environ.get('UPTIME_LOOKBACK_DAYS', '7') or '7')

# Grace period (days) after a target's target_date before a node still running an
# older version is marked as version "shame". Applied globally at evaluation time
# (validators/version_status.py); changing it affects all targets, past and future.
NODE_VERSION_SHAME_GRACE_DAYS = int(os.environ.get('NODE_VERSION_SHAME_GRACE_DAYS', '3') or '3')

# Minimum distinct operators that must be observed running a new stable node
# version before the Grafana sync auto-creates it as the fleet-wide upgrade
# target. Default 1: the first adopter creates the target (product decision).
# The version label is self-reported by the nodes being judged and rewarded,
# so raise this to require corroboration if spoofing ever becomes a concern
# (validators/grafana_service.py).
NODE_VERSION_MIN_OPERATORS_FOR_AUTO_TARGET = int(
    os.environ.get('NODE_VERSION_MIN_OPERATORS_FOR_AUTO_TARGET', '1') or '1'
)

# AWS Health Check IPs - Allow these IPs to bypass ALLOWED_HOSTS
# Required environment variable with AWS internal/metadata service IPs
ALLOWED_CIDR_NETS = get_required_env('ALLOWED_CIDR_NETS').split(',')

# HTTPS/SSL Settings for production
# These settings help Django detect HTTPS when behind a proxy/load balancer
# Always trust the X-Forwarded-Proto header when it's present (for both staging and production)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Use forwarded headers for generating URLs
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Transport security hardening outside of local development: redirect plain
# HTTP to HTTPS and emit HSTS so browsers refuse downgraded connections.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    # Infrastructure health checks may probe over plain HTTP without the
    # X-Forwarded-Proto header; redirecting them would fail deployments.
    SECURE_REDIRECT_EXEMPT = [r'^health/?$']
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False  # other subdomains are not ours to claim
    SECURE_HSTS_PRELOAD = False
    SECURE_CONTENT_TYPE_NOSNIFF = True

# Google reCAPTCHA settings
# Required for contribution submission spam protection
# For development: Use Google's test keys (see .env.example)
# For production: Get real keys at https://www.google.com/recaptcha/admin
RECAPTCHA_PUBLIC_KEY = get_required_env('RECAPTCHA_PUBLIC_KEY')
RECAPTCHA_PRIVATE_KEY = get_required_env('RECAPTCHA_PRIVATE_KEY')

# Silence the test-key system check (a hard error that blocks startup when
# DEBUG=False) in local development, and on deployments that explicitly opt in
# via RECAPTCHA_ALLOW_TEST_KEYS=true (the dev portal runs Google's test keys on
# purpose so QA submissions auto-pass the captcha). Production never sets the
# flag, so accidentally shipping test keys there still refuses to boot.
_RECAPTCHA_TEST_PUBLIC_KEY = '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'
_RECAPTCHA_ALLOW_TEST_KEYS = os.environ.get('RECAPTCHA_ALLOW_TEST_KEYS', '').lower() == 'true'
SILENCED_SYSTEM_CHECKS = []
if RECAPTCHA_PUBLIC_KEY == _RECAPTCHA_TEST_PUBLIC_KEY and (DEBUG or _RECAPTCHA_ALLOW_TEST_KEYS):
    SILENCED_SYSTEM_CHECKS.append('django_recaptcha.recaptcha_test_key_error')

# Cron job authentication token for validator sync endpoint
CRON_SYNC_TOKEN = os.environ.get('CRON_SYNC_TOKEN', '')

# Grafana Cloud (Wall of Shame): observability cross-check for active validators
GRAFANA_BASE_URL = os.environ.get('GRAFANA_BASE_URL', 'https://genlayerfoundation.grafana.net')
GRAFANA_API_TOKEN = os.environ.get('GRAFANA_API_TOKEN', '')
GRAFANA_PROM_DS_UID = os.environ.get('GRAFANA_PROM_DS_UID', 'grafanacloud-prom')
GRAFANA_LOKI_DS_UID = os.environ.get('GRAFANA_LOKI_DS_UID', 'grafanacloud-logs')
# Map our internal network keys to the `network` label used in Grafana queries.
GRAFANA_NETWORK_LABELS = {
    'asimov': os.environ.get('GRAFANA_ASIMOV_LABEL', 'asimov-phase5'),
    'bradbury': os.environ.get('GRAFANA_BRADBURY_LABEL', 'bradbury-phase1'),
}


# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
# Layer-based logging: [API], [DB], [APP]
# DEBUG=true: All logs (requests, queries, app debug)
# DEBUG=false: Only errors and warnings

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'layered': {
            '()': 'tally.middleware.logging_utils.LayeredFormatter',
        },
        'layered_json': {
            '()': 'tally.middleware.logging_utils.LayeredJSONFormatter',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'layered' if DEBUG else 'layered_json',
        },
    },
    'loggers': {
        # Application layer loggers
        'tally.api': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'WARNING',
            'propagate': False,
        },
        'tally.db': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'WARNING',
            'propagate': False,
        },
        'tally.app': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'WARNING',
            'propagate': False,
        },
        'tally.trace': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'WARNING',
            'propagate': False,
        },
        # Silence noisy Django loggers
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
}
