# Generated by Django 5.2.1 on 2025-05-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visible',
            field=models.BooleanField(default=True, help_text='Whether this user should be visible in API responses.'),
        ),
    ]
