# Generated by Django 5.2.1 on 2025-05-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_update_address_field'),
        ('users', '0002_user_visible'),
    ]

    operations = [
    ]
