# Generated by Django 5.2.1 on 2025-05-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_address_constraint'),
        ('users', '0003_merge_0002_update_address_field_0002_user_visible'),
    ]

    operations = [
    ]
