# Generated by Django 5.2.1 on 2025-08-15 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_validator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Validator',
        ),
    ]
