# Generated by Django 5.2.1 on 2025-08-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner_image_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for banner image', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='banner_image_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for banner image (1500x500)', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Public contact email (different from auth email)', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, help_text='User bio/description in markdown format', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_handle',
            field=models.CharField(blank=True, help_text='Discord username', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Whether the email is user-provided (True) or auto-generated (False)'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for profile image', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for profile image (400x400)', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_handle',
            field=models.CharField(blank=True, help_text='Telegram username without @', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_handle',
            field=models.CharField(blank=True, help_text='Twitter/X username without @', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, help_text="User's website URL"),
        ),
    ]
