# Generated by Django 5.2.1 on 2025-08-19 21:47

from django.db import migrations


def mark_autogenerated_emails(apps, schema_editor):
    """Mark all auto-generated emails as unverified"""
    User = apps.get_model('users', 'User')
    
    # Mark emails ending with @ethereum.address as unverified
    User.objects.filter(email__endswith='@ethereum.address').update(is_email_verified=False)
    
    # Mark all other existing emails as verified (assuming they were user-provided)
    User.objects.exclude(email__endswith='@ethereum.address').update(is_email_verified=True)


def reverse_mark_autogenerated_emails(apps, schema_editor):
    """Reverse the email verification marking"""
    User = apps.get_model('users', 'User')
    User.objects.all().update(is_email_verified=False)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_profile_fields'),
    ]

    operations = [
        migrations.RunPython(mark_autogenerated_emails, reverse_mark_autogenerated_emails),
    ]
