# Generated by Django 5.2.1 on 2025-08-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_mark_autogenerated_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedin_handle',
            field=models.CharField(blank=True, help_text='LinkedIn username or profile URL slug', max_length=100),
        ),
    ]
