# Generated by Django 5.2.1 on 2025-08-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_linkedin_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, help_text='User bio/description (plain text)', max_length=500),
        ),
    ]
