# Generated by Django 5.2.1 on 2025-08-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_update_description_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, help_text='User bio/description', max_length=500),
        ),
    ]
