# Generated by Django 5.2.7 on 2025-10-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_populate_referral_codes_for_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_access_token',
            field=models.TextField(blank=True, help_text='Encrypted GitHub access token'),
        ),
        migrations.AddField(
            model_name='user',
            name='github_linked_at',
            field=models.DateTimeField(blank=True, help_text='When GitHub account was linked', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='github_user_id',
            field=models.CharField(blank=True, help_text='GitHub user ID for unique identification', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='github_username',
            field=models.CharField(blank=True, help_text='GitHub username from OAuth', max_length=100),
        ),
    ]
