# Generated by Django 6.0.6 on 2026-06-16 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_ban_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_email',
        ),
    ]
