# Generated by Django 6.0.6 on 2026-06-29 13:48

from django.db import migrations, models


def reset_existing_email_verification(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.all().update(is_email_verified=False, email_verified_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_user_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='When the current email address was verified', null=True),
        ),
        migrations.RunPython(reset_existing_email_verification, migrations.RunPython.noop),
    ]
