# Generated by Django 6.0.6 on 2026-07-29 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('ethereum_auth', '0004_nonce_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingwalletsignup',
            name='acquisition_campaign_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_signups', to='campaigns.campaignlink'),
        ),
        migrations.AddField(
            model_name='pendingwalletsignup',
            name='acquisition_captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingwalletsignup',
            name='acquisition_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
