/**
 * Portal i18n wrapper around the compiled Paraglide runtime
 * (`src/lib/paraglide/`, generated by the Vite plugin from `messages/*.json`).
 *
 * Locale resolution order (compiler `strategy` in vite.config.js):
 * localStorage ("PARAGLIDE_LOCALE") → browser preferred language → English.
 * `setLocale` persists the choice and reloads the page — a deliberate
 * decision so module-scope copy constants (resources.js, journey configs,
 * socialTaskLabels.js, ...) never go stale on an in-place switch.
 */
import { getLocale, setLocale, locales, baseLocale } from './paraglide/runtime.js';
import { es as dfEs, ko as dfKo, zhCN as dfZhCN, tr as dfTr } from 'date-fns/locale';

export { getLocale, setLocale, locales, baseLocale };

export const SUPPORTED_LOCALES = [
  { code: 'en', label: 'English' },
  { code: 'es', label: 'Español' },
  { code: 'ko', label: '한국어' },
  { code: 'zh-Hans', label: '简体中文' },
  { code: 'tr', label: 'Türkçe' },
];

const OG_LOCALES = {
  en: 'en_US',
  es: 'es_ES',
  ko: 'ko_KR',
  'zh-Hans': 'zh_CN',
  tr: 'tr_TR',
};

// date-fns has no `en` entry here on purpose: undefined → its English default.
/** @type {Partial<Record<string, import('date-fns').Locale>>} */
const DATE_FNS_LOCALES = { es: dfEs, ko: dfKo, 'zh-Hans': dfZhCN, tr: dfTr };

/** Open Graph locale tag (og:locale) for the active locale. */
export function ogLocale() {
  return OG_LOCALES[getLocale()] || 'en_US';
}

/** Locale object for date-fns `format`/`formatDistanceToNow` calls. */
export function dateFnsLocale() {
  return DATE_FNS_LOCALES[getLocale()];
}

/**
 * Persist the new locale and reload the current route in that language.
 * @param {string} code
 */
export function setPortalLocale(code) {
  if (!SUPPORTED_LOCALES.some((l) => l.code === code)) return;
  setLocale(code);
}

/** Keep `<html lang>` in sync with the active locale (W3C recommendation). */
export function syncDocumentLanguage() {
  document.documentElement.lang = getLocale();
}

/**
 * @param {unknown} value
 * @param {Intl.NumberFormatOptions} [options]
 */
export function formatNumber(value, options) {
  const n = Number(value);
  if (!Number.isFinite(n)) return '';
  return n.toLocaleString(getLocale(), options);
}

/**
 * Compact notation ("1.2K", "3.4M" — per-locale). Returns null for non-numbers.
 * @param {unknown} value
 */
export function formatCompactNumber(value) {
  if (value == null || value === '') return null;
  const n = Number(value);
  if (!Number.isFinite(n)) return null;
  return new Intl.NumberFormat(getLocale(), {
    notation: 'compact',
    maximumFractionDigits: 1,
  }).format(n);
}

/**
 * @param {string | number | Date} value
 * @param {Intl.DateTimeFormatOptions} [options]
 */
export function formatDate(value, options = { dateStyle: 'medium' }) {
  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) return '';
  return date.toLocaleDateString(getLocale(), options);
}
