# Generated by Django 5.2.6 on 2025-12-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stewards', '0002_workinggroup_workinggroupparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinggroup',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji icon for the working group', max_length=10),
        ),
        migrations.AddField(
            model_name='workinggroup',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the working group'),
        ),
    ]
