# Generated by Django 6.0.2 on 2026-02-26 15:04

from django.db import migrations, models


def populate_action_from_label(apps, schema_editor):
    """Populate action field from label prefix and strip the prefix."""
    ReviewTemplate = apps.get_model('stewards', 'ReviewTemplate')
    for t in ReviewTemplate.objects.all():
        if t.label.startswith('Accept: '):
            t.action = 'accept'
            t.label = t.label[len('Accept: '):]
        elif t.label.startswith('More Info: '):
            t.action = 'more_info'
            t.label = t.label[len('More Info: '):]
        elif t.label.startswith('Reject: '):
            t.action = 'reject'
            t.label = t.label[len('Reject: '):]
        else:
            t.action = 'reject'  # default
        t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stewards', '0006_create_ai_steward'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewtemplate',
            options={'ordering': ['action', 'label']},
        ),
        migrations.AddField(
            model_name='reviewtemplate',
            name='action',
            field=models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('more_info', 'More Info')], default='reject', help_text='Which review action this template is for', max_length=20),
        ),
        migrations.RunPython(populate_action_from_label, migrations.RunPython.noop),
    ]
