# Generated by Django 6.0.4 on 2026-04-22 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0052_contributiontype_required_evidence_url_types'),
        ('stewards', '0009_tier1_review_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='StewardAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('full_review', 'Full Review'), ('propose', 'Propose Only')], max_length=20)),
                ('scope_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steward_assignments', to='contributions.category')),
                ('scope_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steward_assignments', to='contributions.contributiontype')),
                ('steward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='stewards.steward')),
            ],
            options={
                'ordering': ['steward', 'role'],
                'constraints': [models.CheckConstraint(condition=models.Q(('scope_category__isnull', False), ('scope_type__isnull', False), _negated=True), name='steward_assignment_scope_mutually_exclusive'), models.UniqueConstraint(fields=('steward', 'role', 'scope_category', 'scope_type'), name='steward_assignment_unique')],
            },
        ),
    ]
