# Generated by Django 6.0.4 on 2026-04-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stewards', '0011_migrate_permissions_to_assignments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StewardPermission',
        ),
    ]
