# Generated by Django 6.0.6 on 2026-07-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stewards', '0012_feature_candidate_score_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='steward',
            name='tier',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Reviewer'), (2, 'Top-level steward'), (3, 'Apex steward')], default=1),
        ),
    ]
